#!/bin/bash

# Check if command exists in $PATH
# USAGE:
#   home-stack::exists <command>
home-stack::exists() {
  command -v $1 > /dev/null 2>&1
}

# ------------------------------------------------------------------------------
# A tool for bootstraping and managing smart homes
#
# Install Docker
# Install Home Assistant Supervised
# Compose containers
#     - Plex
#     - Portainer
#     - etc
# Controll server
#
# ------------------------------------------------------------------------------

HOME_STACK_ROOT="$(dirname $BASH_SOURCE)"

# Menu system starts here
# Display main menu
main_action=$(whiptail --title "Home Stack" --menu --notags \
  "" 20 78 12 -- \
  "install-docker" "Install Docker" \
  "install-ha-supervised" "Install Home Assistant Supervised" \
  3>&1 1>&2 2>&3)

case $main_action in
  'install-docker')
    source "$HOME_STACK_ROOT/actions/install-docker.bash"
  ;;
  'install-ha-supervised')
    source "$HOME_STACK_ROOT/actions/install-ha-supervised.bash"
  ;;
esac
