#!/bin/bash

echo stopping
exit

HOME_STACK_BIN="$(readlink -f "${BASH_SOURCE[0]}")"
HOME_STACK_DIR="$(dirname "$HOME_STACK_BIN")"

# 'docker-compose.y*ml' matches both .yml and .yaml extensions
DOCKER_COMPOSE=$(home-stack::lookup docker-compose.y*ml)
PROJECT_DIR=$(dirname "$DOCKER_COMPOSE")

# Menu system starts here
# Display main menu
main_action=$(whiptail --title "Home Stack" --menu --notags \
  "" 20 78 12 -- \
  "init" "Install Docker" \
  "install-ha-supervised" "Install Home Assistant Supervised" \
  "add-containers" "Add Containers" \
  "commands" "Control Containers" \
  "update" "Update Home Stack" \
  3>&1 1>&2 2>&3)

case $main_action in
  'init')
    # shellcheck source=./actions/init.sh
    source "$HOME_STACK_DIR/actions/init.sh"
  ;;
  'install-ha-supervised')
    # shellcheck source=./actions/install-ha-supervised.sh
    source "$HOME_STACK_DIR/actions/install-ha-supervised.sh"
  ;;
  'add-containers')
    # shellcheck source=./actions/add-containers.sh
    source "$HOME_STACK_DIR/actions/add-containers.sh"
  ;;
  'commands')
    # shellcheck source=./actions/commands.sh
    source "$HOME_STACK_DIR/actions/commands.sh"
  ;;
  'update')
    # shellcheck source=./actions/update.sh
    source "$HOME_STACK_DIR/actions/update.sh"
  ;;
esac
